"""Claude Code: a `.claude/CLAUDE.md` stub importing AGENTS.md, plus per-skill links.

Claude Code reads AGENTS.md only when no CLAUDE.md exists, so a one-line `@../AGENTS.md`
block in `.claude/CLAUDE.md` shares it. Not the root CLAUDE.md: Copilot reads that too and
then loads the rulebook twice (measured: +5.9k input tokens). Claude loads both locations,
so a user's own root CLAUDE.md keeps working untouched. It reads skills only from `.claude/skills/`,
so each shared `.agents/skills/<n>` is linked there (symlink → junction → copy).
Agents, hooks and MCP (`.claude/agents`, `.claude/settings.json`, `.mcp.json`) are the
shared copies and need nothing extra.
"""
from installer import links, source
from installer.context import Context
from installer.manifest import sha256
from installer.platforms.base import Platform

# Lists the generated links, so git skips them but a user's own skill dirs stay tracked.
SKILLS_GITIGNORE = ".claude/skills/.gitignore"


class ClaudeCode(Platform):
    key = "claude"
    label = "Claude Code"
    binaries = ("claude",)
    next_steps = ("start a new session in the project; .claude/agents/ is discovered "
                  "at startup.")

    def install(self, ctx: Context) -> None:
        print("claude:")
        self._claude_md(ctx)
        names = source.skill_names()
        for name in names:
            self._link_skill(ctx, name)
        rel = SKILLS_GITIGNORE
        path = ctx.target / rel
        ours = ctx.manifest.data["generated"].get(rel)
        if not path.exists() or (ours and sha256(path) == ours.get("sha256")):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("# generated by setup-team.py: links to ../../.agents/skills/\n"
                            + "".join(f"/{n}\n" for n in names) + "/.gitignore\n")
            ctx.manifest.add(rel, self.key, "file", sha256=sha256(path))

    def _claude_md(self, ctx: Context) -> None:
        legacy = ctx.target / "CLAUDE.md"
        if legacy.exists() and legacy.read_text(errors="ignore").startswith(
                source.LEGACY_CLAUDE_MD_MARKER):
            if not ctx.force:
                ctx.writer.report("CLAUDE.md", "skip (old full rulebook — --force migrates "
                                  "it to AGENTS.md)")
                return
            legacy.unlink()  # the whole file was the harness's; AGENTS.md now holds it
            ctx.writer.report("CLAUDE.md", "removed (old rulebook — now AGENTS.md)")
        ctx.block(".claude/CLAUDE.md", source.CLAUDE_STUB.read_text(), platform=self.key)

    def _link_skill(self, ctx: Context, name: str) -> None:
        rel = f".claude/skills/{name}"
        dst = ctx.target / rel
        src = ctx.target / ".agents" / "skills" / name
        ours = ctx.manifest.data["generated"].get(rel)
        if links.points_to(dst, src):
            ctx.writer.report(rel, "ok (linked)")
            ctx.manifest.add(rel, self.key, "link", mode="symlink")
            return
        if dst.exists() or links.is_link(dst):
            stale_copy = ours and ours.get("mode") == "copy"
            if not (ctx.force and (stale_copy or links.is_link(dst))):
                ctx.writer.report(rel, "skip (exists — not a link to .agents/skills)")
                return
            links.remove(dst)
        mode = links.make_link(src, dst)
        info = {"mode": mode}
        if mode == "copy":
            info["tree"] = links.tree_hash(dst)
        ctx.manifest.add(rel, self.key, "link", **info)
        ctx.writer.report(rel, f"ok ({mode} → .agents/skills/{name})")

